(function () {
	ex.define("ex.util.Key", {
		__statics: {
		  names: ['', '', '', '', '', '', '', '', 'Backspace', 'Tab',
		          '', '', '', 'Enter', '', '', 'Shift', 'Control', '', 'PauseBreak',
		          'CapsLock', '', '', '', '', '', '', 'Esc', '', '',
		          '', '', 'Spacebar', 'PageUp', 'PageDown', 'End', 'Home', 'Left', 'Up', 'Right',
		          'Down', '', '', '', '', 'Insert', 'Delete', '', 'Keyb0', 'Keyb1',
		          'Keyb2', 'Keyb3', 'Keyb4', 'Keyb5', 'Keyb6', 'Keyb7', 'Keyb8', 'Keyb9', '', '',
		          '', '', '', '', '', 'A', 'B', 'C', 'D', 'E',
		          'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
		          'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
		          'Z', '', '', '', '', '', 'Numpad0', 'Numpad1', 'Numpad2', 'Numpad3', 
		          'Numpad4', 'Numpad5', 'Numpad6', 'Numpad7', 'Numpad8', 'Numpad9', 'NumpadStar', 'NumpadPlus', '', 'NumpadMinus', 
		          'NumpadPeriod', 'NumpadSlash', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8',
		          'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', '', '', '',
		          '', '', '', '', '', '', '', '', '', '',
		          '', '', '', '', 'NumLck', 'ScrLck', '', '', '', '',
		          '', '', '', '', '', '', '', '', '', '',
		          '', '', '', '', '', '', '', '', '', '',
		          '', '', '', '', '', '', '', '', '', '',
		          '', '', '', '', '', '', 'SemiColon', 'Equal', 'Comma', 'Minus',
		          'Period', 'Question','BackQuote', '', '', '', '', '', '', '', 
		          '', '', '', '', '', '', '', '', '', '', 
		          '', '', '', '', '', '', '', '', '', 'LeftBrace',
		          'Pipe', 'RightBrace', 'SingleQuote'
		          
		          
		          ],
		  Backspace:	 8,
		  Tab:			   9,
		  Enter:		  13,
		  Shift:		  16,
		  Control:	  17,
		  PauseBreak:	19,
		  CapsLock:	  20,
		  Esc:			  27,
		  Spacebar:	  32,
		  PageUp:		  33,
		  PageDown:	  34,
		  End:			  35,
		  Home:			  36,
		  Left:			  37,
		  Up: 			  38,
		  Right:		  39,
		  Down:			  40,
		  Insert:		  45,
		  Delete:		  46,
		  
		  Keyb0: 		48,
		  Keyb1: 		49,
		  Keyb2: 		50,
		  Keyb3: 		51,
		  Keyb4: 		52,
		  Keyb5: 		53,
		  Keyb6: 		54,
		  Keyb7: 		55,
		  Keyb8: 		56,
		  Keyb9: 		57,
		  
		  A: 			              65,
		  B: 			              66,
		  C: 			              67,
		  D: 			              68,
		  E: 			              69,
		  F: 			              70,
		  G: 			              71,
		  H: 			              72,
		  I: 			              73,
		  J: 			              74,
		  K: 									  75,
		  L: 									  76,
		  M: 									  77,
		  N: 									  78,
		  O: 									  79,
		  P: 									  80,
		  Q: 									  81,
		  R: 									  82,
		  S: 									  83,
		  T: 									  84,
		  U: 									  85,
		  V: 									  86,
		  W: 									  87,
		  X: 									  88,
		  Y: 									  89,
		  Z: 									  90,
		  
		  Numpad0: 							96,
		  Numpad1: 							97,
		  Numpad2: 							98,
		  Numpad3: 							99,
		  Numpad4: 							100,
		  Numpad5: 							101,
		  Numpad6: 							102,
		  Numpad7: 							103,
		  Numpad8: 							104,
		  Numpad9: 							105,
		  NumpadStar:						106,
		  NumpadPlus:						107,
		  NumpadMinus:					109,
		  NumpadPeriod:					110,
		  NumpadSlash:					111,
		  
		  F1:							    	112,
		  F2:							  		113,
		  F3:						   			114,
		  F4:						   			115,
		  F5:						   			116,
		  F6:								   	117,
		  F7:									  118,
		  F8:									  119,
		  F9:									  120,
		  F10:                  121,
		  F11: 								  122,
		  F12: 								  123,
		  F13: 								  124,
		  F14:								  125,
		  F15:								  126,
		  
		  NumLck:								144,
		  ScrLck:								145,
		  
		  SemiColon:						186,
		  Equal:								187,
		  Comma:								188,
		  Minus:								189,
		  Period:								190,
		  Question:							191,
		  BackQuote:						192,

		  LeftBrace:						219,
		  Pipe:								  220,
		  RightBrace:						221,
		  SingleQuote:					222
		}
	});
}());
